"""ID3 tags, written after ffmpeg has produced the file.

mutagen rather than ``ffmpeg -metadata``: it gives frame-level control, can
attach cover art without a second input stream, and is a pure-python wheel.
"""

from __future__ import annotations

import mimetypes
from pathlib import Path

from earmark.extract.meta import Metadata

ALBUM = "earmark"


def write(
    path: Path,
    meta: Metadata,
    duration_seconds: float | None = None,
    album: str | None = None,
    track: int | None = None,
    cover: Path | None = None,
) -> None:
    from mutagen.id3 import (
        APIC, COMM, ID3, TALB, TCON, TDRC, TENC, TIT2, TLEN, TPE1, TPE2, TRCK, WOAS,
    )
    from mutagen.id3 import ID3NoHeaderError

    from earmark import __version__

    try:
        tags = ID3(str(path))
    except ID3NoHeaderError:
        tags = ID3()

    tags.add(TIT2(encoding=3, text=meta.title))
    tags.add(TPE1(encoding=3, text=meta.author or meta.site or "Unknown Author"))
    tags.add(TALB(encoding=3, text=album or ALBUM))
    # A constant album artist groups everything under one entry in a player.
    tags.add(TPE2(encoding=3, text=ALBUM))
    tags.add(TCON(encoding=3, text="Podcast"))
    tags.add(TENC(encoding=3, text=f"earmark {__version__}"))
    if meta.date:
        tags.add(TDRC(encoding=3, text=meta.date))
    if duration_seconds:
        tags.add(TLEN(encoding=3, text=str(int(duration_seconds * 1000))))
    if meta.source:
        tags.add(COMM(encoding=3, lang="eng", desc="", text=f"Generated by earmark from {meta.source}"))
        if meta.source.startswith(("http://", "https://")):
            tags.add(WOAS(url=meta.source))
    if track:
        tags.add(TRCK(encoding=3, text=str(track)))
    if cover and Path(cover).exists():
        mime = mimetypes.guess_type(str(cover))[0] or "image/jpeg"
        tags.add(APIC(encoding=3, mime=mime, type=3, desc="Cover", data=Path(cover).read_bytes()))

    # ID3v2.3: Apple's tooling has always been happiest with it, and nothing
    # written here needs a 2.4-only frame.
    tags.save(str(path), v2_version=3)


def read(path: Path) -> dict:
    from mutagen.id3 import ID3

    tags = ID3(str(path))
    return {frame: str(tags[frame]) for frame in tags}
